# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'DemoFbLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoFbLogin
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'BarcodeScanner'
  pod 'GoogleSignIn'

  target 'DemoFbLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoFbLoginUITests' do
    # Pods for testing
  end

end
